apiVersion: v1
kind: Service
metadata:
  name: backend-core-service
  namespace: toeic-system
  labels:
    app: backend-core
spec:
  type: ClusterIP
  selector:
    app: backend-core
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

