apiVersion: v1
kind: Service
metadata:
  name: backend-ai-service
  namespace: toeic-system
  labels:
    app: backend-ai
spec:
  type: ClusterIP
  selector:
    app: backend-ai
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP

